#!/bin/sh
#
# A hook script that is called after a successful
# checkout is made.

if [ $3 == 1 ]
then
    # This is a branch checkout
    if [ $1 != $2 ]
    then
        REFS="Files changed"
    else
        REFS="No files changed"
    fi
    growlnotify -t "Checked out $(git branch | grep "*" | sed "s/* //")" -m "$REFS" -n "git-growl" --image ~/.git-growl/images/git_icon.png
else
    # This is a file checkout
    growlnotify -t "Checked out file" -m "$REFS" -n "git-growl" --image ~/.git-growl/images/git_icon.png
fi
#echo $(git rev-parse --symbolic-full-name --abbrev-ref @{u});
