#!/bin/sh
#
# An example hook script that is called after a successful
# merge is made.

growlnotify -t "Merge Successful" -m "On branch $(git branch | grep "*" | sed "s/* //")" -n "git-growl" --image ~/.git-growl/images/git_icon.png

