#!/bin/sh
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, rename this file to "post-commit".

growlnotify -t "Commit Successful" -m "$(git log -1 --pretty=format:"%s")" -n "git-growl" --image ~/.git-growl/images/git_icon.png

