#!/bin/sh
#
# An example hook script that is called after a successful
# merge is made.

growlnotify -t "Merge on $(git branch | grep "*" | sed "s/* //")" -m "git diff --stat HEAD HEAD~1 | awk END{print}" -n "git-growl" --image ~/.git-growl/images/git_icon.png

