#!/bin/sh
#
# This hook displays a growl notification with commit information

growlnotify -t "Commit on $(git branch | grep "*" | sed "s/* //")" -m "$(git log -1 --pretty=format:"%s")" -n "git-growl" --image ~/.git-growl/images/git_icon.png

