#!/bin/sh
#
# This hook shows a message when a successful
# checkout is made.

if [ $3 == 1 ]
then
    # This is a branch checkout
    if [ $1 != $2 ]
    then
        REFS="Files changed"
    else
        REFS="No files changed"
    fi
    notify-send "Checked out $(git branch | grep "*" | sed "s/* //")" "$REFS" -i ../images/git_icon.png
else
    # This is a file checkout
    notify-send "Checked out file" "$REFS" -i ../images/git_icon.png
fi
#echo $(git rev-parse --symbolic-full-name --abbrev-ref @{u});
