#!/bin/sh
#
# This hook displays a growl notification with commit information

notify-send "Commit on $(git branch | grep "*" | sed "s/* //")" "$(git log -1 --pretty=format:"%s")" -i ~/.git-growl/images/git_icon.png

