#!/bin/sh
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, rename this file to "post-commit".

notify-send "Commit Successful" "$(git log -1 --pretty=format:"%s")" -i ~/Dropbox/git/git_icon.png

