#!/bin/bash
#
# This hook shows a message when a successful
# checkout is made.

GIT_GROWL_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ $3 == 1 ]
then
    # This is a branch checkout
    if [ $1 != $2 ]
    then
        REFS="Files changed"
    else
        REFS="No files changed"
    fi
    notify-send "Checked out $(git branch | grep "*" | sed "s/* //")" "$REFS" -i $GIT_GROWL_DIR/images/git_icon.png
else
    # This is a file checkout
    notify-send "Checked out file" "$REFS" -i $GIT_GROWL_DIR/images/git_icon.png
fi
#echo $(git rev-parse --symbolic-full-name --abbrev-ref @{u});

