#!/bin/bash
#
# This hook displays a message when a successful
# merge is made.

kdialog --passivepopup "$(git diff --stat HEAD@{1} HEAD@{0} | awk END{print})" 5 --title "Merge on $(git branch | grep "*" | sed "s/* //")" --icon ~/.git-growl/images/git_icon.png --name "git-growl"

